name: btf
version: 0.0.1
author: Timothy A. Davis
description: Permutes an unsymmetric matrix (square or rectangular) into its block upper triangular form.
homepage: http://www.cise.ufl.edu/research/sparse/btf/
dependencies:
  unittest: any
